### PR TITLE
[template] expand note of highlighter conflicts for alacritty

### PR DESCRIPTION
**Pull request by kaseiwang**
Alacritty has #28 issue too.

### CODE REVIEW

**Comment by ericbn** [comment]
I'm actually in favor of removing the `cursor` highlighter. Does it do any good in any situation? Not needed in MacOS iTerm or Terminal either.

@Eriner, thoughts?

**Comment by kaseiwang** [comment]
Or just remove it from default config?

**Comment by ericbn** [comment]
@Eriner, @Plloi, @PatTheMav, what do you think about removing the cursor highlighter from the zimrc template? ☝️

**Comment by PatTheMav** [comment]
@ericbn Personally I'm fine with removing it as I use near exclusively use macOS, so I'm not affected. 

Also I've yet to see this specific functionality of `zsh-syntax-highlighting`, so you'd have my vote to remove it from default (!) settings - people can still add it if necessary.

**Comment by Plloi** [comment]
I pulled it from my config due the issues it causes, so i may be a little biased... But I say pull it.

**Comment by ericbn** [comment]
`cursor` highlighter removed.

@Plloi, any news from @Eriner?

**Comment by Plloi** [comment]
...about what? though any contact i have is have is here in the comments.

**Comment by ericbn** [comment]
Oh sorry, I don't know why I had the impression you two worked together or something like that :blush:

**Pull request closed without merging**
