### PR TITLE
archive: add support for archiving multiple files

### PR DESCRIPTION
**Pull request by Konfekt**
See https://github.com/zimfw/zimfw/issues/306

It is POSIX shell syntax.

### CODE REVIEW

**Comment by Konfekt** [comment]
Be aware that for example `tar.xz` does currently not support archiving directories, but only files.

**Comment by ericbn** [comment]
You should respect the project's [code style guide] (https://github.com/zimfw/zimfw/wiki/Code-Style-Guide). Projects usually have one, with most parts of it explicitly documented in a style guide, but some more subtle ones implicitly visible in the code itself. Respecting that is respecting the developers that came before you...

**Comment by Plloi** [comment]
@Konfekt here's what is I see style wise:
* Variables not always braced
* Case format altered
* Comments removed, not updated (personal peeve)

**Comment by Konfekt** [comment]
Thank you. I updated this pull request accordingly.

**Comment by ericbn** [comment]
@Konfekt, if you're making a contribution to a repo (specially if it's the first one), you should push just the specific change you're proposing. You proposed supporting multiple files as arguments for `archive`, but you came up with lots of other changes:

* Code is inclosed in `archive() {...}`. This is an autoloaded function file, so no need for that.
* You use `[...]`. We prefer `((...))` for arithmetic conditions and `[[...]]` for other condition evaluations.
* You changed the error messages. I prefer we keep them as they are.
* You're creating a file with a different name if the provided name already exists. I prefer we keep it as we're doing.
* You changed the logic of most of the tools by changing the parameters (e.g. you use `tar j`, we use `tar --use-compress-program=bzip2` because we alias pbzip2 to bzip2 if the tool is available, and we want to take advantage of that), or by the way the tools are called. Each one of these changes deserve a separate discussion.
* You're forcing predefined extensions (e.g. you force `"${name}.tar.gz"` even if the provided extension was `.tgz`). We don't do that, and I prefer we keep it this way.
* You added support for `.{tZ,tar.Z,Z,compress,lzo}` files. That's great, but should be in a separate pull request with a separate discussion, as I think we should also update `unarchive` and `README.md` accordingly.

One more note: you're not treating the `files` array correctly, as it's not being expanded as different parameters when the tools are called with `${files}` at the end. Oh, and the extra `shift`s you have inside `case...esac` are unnecessary, as you're already doing one in the beginning of the function.

**Comment by Konfekt** [comment]
Thank you for your corrections. One final doubt:

> One more note: you're not treating the files array correctly, as it's not being expanded as different parameters when the tools are called with ${files}

Please help me understand why it is treated incorrectly. How would it be treated correctly?

**Comment by Plloi** [comment]
> * You use `[...]`. We prefer `((...))` for arithmetic conditions and `[[...]]` for other condition evaluations.

I feel like this one should be added to the style guide

**Comment by Konfekt** [comment]
Thank you!

**Comment by ericbn** [comment]
@Plloi, good point. Just updated the [style guide](https://github.com/zimfw/zimfw/wiki/Code-Style-Guide).

@Konfekt, you're welcome!

**Pull request closed without merging**
