### PR TITLE
[Completion] Add custom SPROMPT

### PR DESCRIPTION
**Pull request by AtomicCoding**
Sets colored SPROMPT by default and allows for user override.

### CODE REVIEW

**Comment by AtomicCoding** [comment]
@ericbn @Eriner Thoughts?

**Comment by ericbn** [comment]
Thanks for your suggestion, @AtomicCoding. I prefer just going with

    SPROMPT='zsh: correct %F{red}%R%f to %F{green}%r%f [nyae]? '

and having no extra configuration. (And using color names instead of numbers)

**Comment by AtomicCoding** [comment]
@ericbn New commit. Changed to an override like method so the user doesn't have to deal with manually overriding SPROMPT after completion is loaded.

**Comment by ericbn** [comment]
Not sure I like this approach of having an extra config var.

Unfortunately checking with `(( ! ${+SPROMPT} )) && SPROMPT='... '` does not work as the var is already pre-set by zsh.

**Comment by AtomicCoding** [comment]
@Eriner Thoughts?

**Comment by AtomicCoding** [comment]
@ericbn Changed to `if [ ${SPROMPT} = '(Default Config)' ]; then SPROMPT='(Color Config)'; fi`. Thoughts?

**Comment by ericbn** [comment]
My 2 cents: Simpler is better I think. These 3 lines of code could be just 1 line in the `.zimrc` file. And the user would get an "unexpected" behavior if he tries to set the default before loading zim.

**Comment by AtomicCoding** [comment]
@ericbn 
Got it! Moved SPROMPT setting to zimrc.
Looks like this:
```zsh
# Set custom completion prompt
SPROMPT="zsh: correct %F{red}%R%f to %F{green}%r%f [nyae]? "
```

**Comment by ericbn** [comment]
Merged with changes (this is a spelling correction prompt, not a "completion prompt").

**Pull request closed without merging**
