### PR TITLE
Updated Plugin Loading

### PR DESCRIPTION
**Pull request by AtomicCoding**
Updated the plugin loading system to load plugins with `{plugin name}.plugin.zsh` and `{plugin name}.zsh` in order to improve compatibility.

### CODE REVIEW

**Comment by AtomicCoding** [comment]
@Brottweiler Sorry! Working on it right now!

**Comment by AtomicCoding** [comment]
Fixed it! Sorry!

**Comment by AtomicCoding** [comment]
@ericbn @Eriner Ping

**Comment by ericbn** [comment]
I would not merge the logo. I like the idea for the init code. Actually I was working on something similar:

    for zmodule_file (${zmodule_dir}/${zmodule}.zsh-theme ${zmodule_dir}/init.zsh ${zmodule_dir}/${zmodule}.zsh ${zmodule_dir}/${zmodule}.sh ${zmodule_dir}/${zmodule}.plugin.zsh); do
      [[ -f ${zmodule_file} ]] && source ${zmodule_file} && break
    done

@Eriner, thoughts?

**Comment by AtomicCoding** [comment]
@ericbn Just made some changes to prioritize `.plugin.zsh`. And prepend zsh- to the plugin script if all else fails.

**Comment by Eriner** [comment]
From a performance perspective, due to the structuring of the conditionals, this won't cause any unecessary disk I/O. I haven't read over the code maticuliously and I'll wait to see what @ericbn says, but the concept and basic structure has a :+1: from me.

**Comment by AtomicCoding** [comment]
@ericbn @Eriner 
Would it be ok to replace the last `elif` with an `else`, I think it would be better to tell people if a plugin isn't being loaded rather than if a plugin's directory doesn't exist.

**Comment by Eriner** [comment]
Closes #135

**Comment by ericbn** [comment]
@Eriner, I'm more in favor of the `for` notation, as we can take advantage of globs and it also looks more concise. What do you think?

I like the idea of trying to match a `zsh-` prefix too. This is what I suggest:

    local zmodule_dir
    # ...
    zmodule_dir=${ZIMFW_HOME}/modules/${zmodule}
    if [[ ! -d ${zmodule_dir} ]]; then
      print "No such module \"${zmodule}\"." >&2
    else
      for zmodule_file (${zmodule_dir}/{,zsh-}${zmodule}.zsh-theme \
          ${zmodule_dir}/init.zsh \
          ${zmodule_dir}/{,zsh-}${zmodule}.{z,}sh \
          ${zmodule_dir}/{,zsh-}${zmodule}.plugin.zsh); do
        if [[ -f ${zmodule_file} ]]; then
          source ${zmodule_file}
          break
        fi
      done
    fi

@AtomicCoding, it is valid to have for example a module with just a `functions` subdir, but no init script, so that's why we don't fail if that case.

---

@Eriner, a side note partially related to this change:  I've been actually working on the "distributed modules" loading mechanism for zim, and I extracted the code above from that. Maybe I should push that to a `develop` branch so we can start looking at it together...

**Comment by AtomicCoding** [comment]
@ericbn I changed some of the priorities and had zmodule_dir be immediately set after being declared because (this might just be me) ZSH echoing the value of it for some reason when it wasn't set like that, either way, here it is:
```zsh
    local zmodule_dir=${ZIM_HOME}/modules/${zmodule}
    if [[ ! -d ${zmodule_dir} ]]; then
      print "No such module \"${zmodule}\"." >&2
    else
      for zmodule_file (${zmodule_dir}/init.zsh \
          ${zmodule_dir}/{,zsh-}${zmodule}.plugin.zsh \
          ${zmodule_dir}/{,zsh-}${zmodule}.zsh-theme \
          ${zmodule_dir}/{,zsh-}${zmodule}.{z,}sh); do
        if [[ -f ${zmodule_file} ]]; then
          source ${zmodule_file}
          break
        fi
      done
    fi
```

**Comment by AtomicCoding** [comment]
@ericbn Most plugins usually have an init.zsh or (module name).plugin.zsh, so why not prioritize those?

**Comment by AtomicCoding** [comment]
@ericbn @Eriner Just committed the for loop system. I'm using it on my installation and all seems to be ready to merge!

**Comment by AtomicCoding** [comment]
Sorry, messed up the pull request

**Comment by AtomicCoding** [comment]
Reopening it soon...

**Comment by AtomicCoding** [comment]
New pull request at #257. Sorry, tried to clear commit tree. Can be merged cleanly now, however.

**Pull request closed without merging**
