### PR TITLE
add zimfw doctor to check for common issues

### PR DESCRIPTION
**Pull request by Konfekt**
start with the probable loading of compinit in system configuration
files

As suggested at https://github.com/zimfw/zimfw/issues/309#issuecomment-579511947

### CODE REVIEW

**Comment by ericbn** [comment]
@Konfekt, please change the files under `src/`. The new function can be under a `src/stage2/50_zimfw_doctor.zsh.erb` file. Then run `make`. If you don't have Ruby installed, you can use gitpod.io/#github.com/zimfw/zimfw as IDE, and run `make` from the command line.

**Comment by Konfekt** [comment]
Okay, I added the erb file in the place indidcated. However, `make` deleted the lines of `zimfw()` to document and start `doctor`, therefore I manualy added them back.

**Comment by ericbn** [comment]
@Konfekt, these lines must be added to `src/stage2/80_zimfw.zsh.erb`  :- )

**Comment by Konfekt** [comment]
Okay, that makes perfect sense. Updated accordingly.

**Comment by ericbn** [comment]
Although [I suggested this myself before](https://github.com/zimfw/zimfw/issues/309#issuecomment-579511947), I still want more opinions, and maybe also wait for a few more use cases for this `zimfw action` action before merging this. Want to make sure we're not bloating our tool.

@Eriner, thoughts?

**Comment by Eriner** [comment]
I don't have any particular aversion to adding things like this. Gotta start somewhere, right?

**Comment by ericbn** [comment]
Maybe common issues should be documented in a Troubleshooting page at https://github.com/zimfw/zimfw/wiki or in our [website docs](https://zimfw.sh/docs/).

**Comment by Konfekt** [comment]
Yes, sounds reasonable.

**Review by X8Pi — APPROVED** [review]
prit(d6si)go

**Comment by ericbn** [comment]
Moved this code to our automatic installation script. Also, the warning about `compinit` and our `completion` module was added to our README.md file.

**Pull request closed without merging**
