### PR TITLE
[Zim Update] Color output and add support for plain git repos

### PR DESCRIPTION
**Pull request by AtomicCoding**
[asciicast](https://asciinema.org/a/UPZvJ20ujAXlGqeIhCd9bvIOy)
Colors output and adds support for plain git repos through umodules array which can be set in the zimrc along with going back to the previous directory you were in when done and when quit.

### CODE REVIEW

**Comment by AtomicCoding** [comment]
@ericbn @Eriner Thoughts?

**Comment by ericbn** [comment]
Thanks for your ideas to the project! This one is actually [something we've been discussing for more than a year](https://github.com/zimfw/zimfw/issues/88).

[As I mentioned before](https://github.com/zimfw/zimfw/pull/266#issuecomment-382205449), I'm working on a version of this for a few months now and I'll push it to a develop branch soon. (I covered colors for successful and failed operations too)

**Comment by ericbn** [comment]
Just as a preview, this is how my update routine output looks like:

screen shot 2018-05-08 at 19 29 45

**Comment by AtomicCoding** [comment]
@ericbn That looks a lot nicer! Is there an ETA on the develop branch and should I close the pull?

**Pull request closed without merging**
