### PR TITLE
Make installation step easier to follow and show mechanism..

### PR DESCRIPTION
**Pull request by Piping**
Currently the installation steps is a bit confusing and requires some digging of the code..

### CODE REVIEW

**Comment by Plloi** [comment]
I think you've got some commit bleed here.

**Comment by Piping** [comment]
Should I merge these commits into one?

**Comment by Plloi** [comment]
@Piping  No, but it you looks like you added more to the pull than intended. (the additional sub modules and the changes to init.zsh and login_init.zsh)

**Comment by Piping** [comment]
@Plloi  I see, let me make a new branch and clean it a bit!

**Pull request closed without merging**
