### PR TITLE
Improve issue template and add the editorconfig

### PR DESCRIPTION
**Pull request by deltaxflux**
Well I deleted my branch so I can't edit my old pull request. Anyway I have changed all required points and I hope that you are now happy with it. 

I just edit following lines:
* **10-10** `#### Output of zmanage info:` -> edited 
* **26-27** `#### Do you want to request a *feature* or report a *bug*?` -> deleted 
* **29-30** `#### If the current behaviour is a bug, please provide the steps...` -> edited 
* **34-34** `### Images or other information` -> deleted

I will close my first pull request and keep the second pull request open. 
Regards, deltax

### CODE REVIEW

**Comment by Plloi** [comment]
your editorconfig sets indent style to tabs, this repo's style guide calls out 2 spaces (https://github.com/zimfw/zimfw/wiki/Code-Style-Guide#indentation)

**Comment by deltaxflux** [comment]
Yeah I know and I want to discuss this. Tabs are in general easier to handle and it is also easier to setup in the personal editorconfig. In my opinion there is no argument why you should use spaces instead of tabs but if it is an issue I will change it back to tabs.

**Comment by Plloi** [comment]
In that case it should have been discussed instead of slipping it into a pull request >.>

**Comment by deltaxflux** [comment]
Maybe but if @Eriner don't like it he can still change it.

**Comment by ericbn** [comment]
If we want to have an `.editorconfig`, I think it should be:

```
# editorconfig.org
root = true

[*]
charset = utf-8
end_of_line = lf
indent_size = 2
indent_style = space
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
trim_trailing_whitespace = false
```

(@deltaxflux, you don't need to close and open a new PR when you want to change something. Just push a new commit, or amend the existing ones, and push to your same branch.)

**Comment by deltaxflux** [comment]
But this is not possible if I have deleted my repository. Anyway I change the editorconfig ( I don't see any reason but I will do it) and push again.

**Comment by deltaxflux** [comment]
**Done.**

**Comment by ericbn** [comment]
@deltaxflux, there will always be reasons to use tabs or spaces, and as I see this, there's not settled best option as well as there's no common agreement on what is the best option.

Now, if we cannot agree on what is best the one, at least we could try to agree that making a first contribution to a repository with all its code indented with spaces ([as most are](https://thenewstack.io/spaces-vs-tabs-a-20-year-debate-and-now-this-what-the-hell-is-wrong-with-go/)) that proposes the change to tabs, is starting in a very tricky territory... 😀

**Comment by deltaxflux** [comment]
Yeah I have improved everything you wanted. Time to merge :)

**Comment by ericbn** [comment]
@Eriner, I'll wait for your review here before merging.

**Comment by deltaxflux** [comment]
Ok good, 
Thanks for your time.

Regards,

deltax

**Comment by ericbn** [comment]
@deltaxflux, I still think the `ISSUE_TEMPLATE.md` can be refined. The text is asking twice for "In a terminal, run 'zmanage info' and paste the output..." And for example, there's no need to ask for 'zmanage info' or the .zimrc or .zshrc file contents when someone is filing a feature request.

**Comment by Eriner** [comment]
It would be nice if Github had different issue templates for different issue classes (bug vs feature request vs RFC/discussion). This mostly looks good. I'll leave the last bits of refinement to your judgement, @ericbn.

**Comment by deltaxflux** [comment]
@ericbn  Is there anything I should change?

Regards,

deltax

**Comment by ericbn** [comment]
@deltaxflux, I still think there's room for improvements in the ISSUE_TEMPLATE.

Some I think are great and close to what you're proposing:
* [caskroom/homebrew-cask](https://github.com/caskroom/homebrew-cask/blob/master/.github/ISSUE_TEMPLATE.md): The "General troubleshooting steps" at the beginning are very helpful and would filter some common issues. I like the general structure of the titles too.
* [Urigo/angular-meteor](https://github.com/Urigo/angular-meteor/blob/master/.github/ISSUE_TEMPLATE.md): This has a clear separation of bugs and features.

**Pull request closed without merging**
